version: '3.8'

services:
  frontend:
    image: node:21
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  backend:
    image: node:21
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=<YOUR_MONGO_URI>
